models/Event.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "event".
 *
 * @property integer $id
 * @property integer $deviceId
 * @property integer $flagId
 * @property string $ip
 * @property string $created
 *
 * @property Flag $flag
 * @property Device $device
 */
class Event extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'event';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['deviceId', 'flagId', 'ip'], 'required'],
            [['deviceId', 'flagId'], 'integer'],
            [['ip'], 'string'],
            [['created'], 'safe'],
            [['flagId'], 'exist', 'skipOnError' => true, 'targetClass' => Flag::className(), 'targetAttribute' => ['flagId' => 'id']],
            [['deviceId'], 'exist', 'skipOnError' => true, 'targetClass' => Device::className(), 'targetAttribute' => ['deviceId' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'deviceId' => 'Numer seryjny urządzenia',
            'flagId' => 'Flaga',
            'ip' => 'Adres IP',
            'created' => 'Data utworzenia',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFlag()
    {
        return $this->hasOne(Flag::className(), ['id' => 'flagId']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDevice()
    {
        return $this->hasOne(Device::className(), ['id' => 'deviceId']);
    }
}

controllers/EventController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Event;
use app\models\EventSearch;
use app\models\Device;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * EventController implements the CRUD actions for Event model.
 */
class EventController extends Controller {

    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Event models.
     * @return mixed
     */
    public function actionIndex() {
        $searchModel = new EventSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Event model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id) {
        return $this->render('view', [
                    'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Event model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate() {
        $model = new Event();

        if ($model->load(Yii::$app->request->post())) {
            $model->ip = Yii::$app->request->userIP;
            if ($model->save()) {
                $device = Device::find()->where(['id' => $model->deviceId])->one();
                $device->modified = null;
                $device->save();
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            return $this->render('create', [
                        'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Event model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id) {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                        'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Event model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id) {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Event model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Event the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = Event::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

}

controllers/RestController.php
<?php

namespace app\controllers;

use yii\rest\ActiveController;
use app\models\Flag;
use app\models\Device;
use app\models\Event;
use yii\db\Query;
use Yii;

class RestController extends ActiveController {

    public $modelClass = 'app\models\Flag';

    public function actionTest($id) {
        $model = new Flag();
        return $model->findAll(['id' => $id]);
    }

    public function actionDeviceList($q = null, $id = null) {
        $out = ['results' => ['id' => '', 'text' => '']];
        if (!is_null($q)) {
            $query = new Query;
            $query->select('id, sn AS text')
                    ->from('device')
                    ->where(['like', 'sn', $q])
                    ->limit(20);
            $command = $query->createCommand();
            $data = $command->queryAll();
            $out['results'] = array_values($data);
        } elseif ($id > 0) {
            $out['results'] = ['id' => $id, 'text' => Device::find($id)->name];
        }
        return $out;
    }

    public function actionSubcat() {
        $deviceId = \Yii::$app->request->Post()['depdrop_parents'];

        $lastEvent = Event::find()->where(['deviceId' => $deviceId])->orderBy('created DESC')->one();
        if ($lastEvent) {
            $flagList = $lastEvent->flag->children;
            if ($flagList) {
                return ['output' => $flagList];
            } else {
                return ['output' => [['id' => 'null', 'name' => 'Urządzenie jest na końcowym etapie. Nie możesz dodać nowego zdarzenia.']]];
            }
        } else {
            $flagModel = new Flag();
            return ['output' => $flagModel->HeadFlags];
        }
    }

    public function actionAddEvent($sn, $flagName) {
        $flag = Flag::find()->where(['name' => $flagName])->one();
        if (!$flag) {
            return ['message' => 'Podana flaga nie istnieje.'];
        }

        $device = Device::find()->where(['sn' => $sn])->one();
        if (!$device) {
            $device = new Device;
            $device->sn = $sn;
            $device->save();
        }

        //Jeżeli urządzenie nie posiada flag sprawdzamy czy użytkownik podał jedną z początkowych flag
        if (!$device->events) {
            $flagModel = new Flag();
            $headFlags = $flagModel->HeadFlags;

            $exist = false;
            foreach ($headFlags as $key => $value) {
                if ($flagName == $value['name']) {
                    $exist = true;
                }
            }

            if (!$exist) {
                return ['message' => 'Podana flaga nie może być przypisana. Urządzenie znajduje się na etapie, który na to nie pozwala.'];
            } else {
                $eventModel = new Event();
                $eventModel->deviceId = $device->id;
                $eventModel->flagId = $flag->id;
                $eventModel->ip = Yii::$app->request->userIP;
                $eventModel->save();

                //Aktualizacja daty modyfikacji urządzenia
                $device = Device::find()->where(['id' => $device->id])->one();
                $device->modified = null;
                $device->save();

                return $eventModel;
            }
            //Urządzenie posiada już inne flagi
        } else {
            $lastEvent = Event::find()->where(['deviceId' => $device->id])->orderBy('created DESC')->one();
            $flagList = $lastEvent->flag->children;
            if (!$flagList) {
                return ['message' => 'Podana flaga nie może być przypisana. Urządzenie znajduje się na etapie, który na to nie pozwala.'];
            } else {
                $exist = false;
                foreach ($flagList as $key => $value) {
                    if ($flagName == $value['name']) {
                        $exist = true;
                    }
                }
                if (!$exist) {
                    return ['message' => 'Podana flaga nie może być przypisana. Urządzenie znajduje się na etapie, który na to nie pozwala.'];
                } else {
                    $eventModel = new Event();
                    $eventModel->deviceId = $device->id;
                    $eventModel->flagId = $flag->id;
                    $eventModel->ip = Yii::$app->request->userIP;
                    $eventModel->save();

                    //Aktualizacja daty modyfikacji urządzenia
                    $device = Device::find()->where(['id' => $device->id])->one();
                    $device->modified = null;
                    $device->save();

                    return $eventModel;
                }
            }
        }
    }

}

views/event/_form.php
<?php

use yii\helpers\Html;
//use yii\widgets\ActiveForm;
use kartik\widgets\ActiveForm;
use app\models\Flag;
use kartik\widgets\Select2; // or kartik\select2\Select2
use yii\web\JsExpression;
use yii\helpers\Url;
use kartik\widgets\DepDrop;

/* @var $this yii\web\View */
/* @var $model app\models\Event */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="event-form">

    <?php
    $form = ActiveForm::begin();
    $flagModel = new Flag();
    $flagList = $flagModel->find()->select(['name', 'id'])->indexBy('id')->column();
    ?>

    <?php
    echo $form->field($model, 'deviceId')->widget(Select2::classname(), [
        'options' => ['placeholder' => 'Wpisz numer seryjny, aby wyszukać urządzenie ...'],
        'pluginOptions' => [
            'allowClear' => true,
            'minimumInputLength' => 1,
            'ajax' => [
                'url' => Url::to(['rest/device-list']),
                'dataType' => 'json',
                'data' => new JsExpression('function(params) { return {q:params.term}; }')
            ],
        ],
    ]);
    ?>

    <?=
        $form->field($model, 'flagId')->widget(DepDrop::className(), [
            'type' => DepDrop::TYPE_SELECT2,
            'pluginOptions' => [
                'depends' => [Html::getInputId($model, 'deviceId')],
                'initialize' => isset($model->flagId) ? true : false,
                'initDepends' => [Html::getInputId($model, 'deviceId')],
                'placeholder' => 'Wybierz',
                'url' => Url::to(['rest/subcat']),
            ],
            'select2Options' => [
                'pluginOptions' => [
                    'width' => '100%',
                ]
            ],
        ]);
        ?>

    <?= ''// $form->field($model, 'flagId')->dropDownList($flagList, ['prompt' => 'Wybierz flagę']); ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Dodaj' : 'Zapisz', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/event/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\EventSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="event-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'deviceId') ?>

    <?= $form->field($model, 'flagId') ?>

    <?= $form->field($model, 'ip') ?>

    <?= $form->field($model, 'created') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/event/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Event */

$this->title = 'Dodaj zdarzenie';
$this->params['breadcrumbs'][] = ['label' => 'Events', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="box">
    <div class="box-header with-border">
    </div><!-- /.box-header -->
    <div class="box-body">
        <div class="event-create">

            <?=
            $this->render('_form', [
                'model' => $model,
            ])
            ?>

        </div>
    </div>
</div>

views/event/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $searchModel app\models\EventSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Zdarzenia';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="box">
    <div class="box-header with-border">
        <h3 class="box-title">Lista zdarzeń</h3>
        <div class="box-tools pull-right">
            <?= Html::a('Dodaj zdarzenie', ['create'], ['class' => 'btn btn-success']) ?>
        </div><!-- /.box-tools -->
    </div><!-- /.box-header -->
    <div class="box-body">
        <div class="event-index">
            <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
            <?=
            GridView::widget([
                'dataProvider' => $dataProvider,
                'filterModel' => $searchModel,
                'columns' => [
                    ['class' => 'yii\grid\SerialColumn'],
                    [
                        'attribute' => 'deviceId',
                        'label' => 'Numer seryjny urządzenia',
                        'value' => 'device.sn',
                    ],
                    [
                        'attribute' => 'flagId',
                        'label' => 'Flaga',
                        'value' => 'flag.name',
                        'filter' => ArrayHelper::map(app\models\Flag::find()->asArray()->all(), 'id', 'name'),
                    ],
                    'ip:ntext',
                    'created',
                    [
                        'class' => 'yii\grid\ActionColumn',
                        'template' => '{view} {delete}'
                    ],
                ],
            ]);
            ?>
        </div>
    </div>
</div>

views/event/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Event */

$this->title = 'Update Event: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Events', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="event-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/event/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Event */

$this->title = 'Zdarzenie urządzenia: ' . $model->device->sn;
$this->params['breadcrumbs'][] = ['label' => 'Events', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="box">
    <div class="box-header with-border">
        <h3 class="box-title">Przegląd zdarzenia</h3>
        <div class="box-tools pull-right">
            <?=
                Html::a('Usuń', ['delete', 'id' => $model->id], [
                    'class' => 'btn btn-danger',
                    'data' => [
                        'confirm' => 'Are you sure you want to delete this item?',
                        'method' => 'post',
                    ],
                ])
                ?>
        </div><!-- /.box-tools -->
    </div><!-- /.box-header -->
    <div class="box-body">
        <div class="event-view">
            <p>
                
                
            </p>

            <?=
            DetailView::widget([
                'model' => $model,
                'attributes' => [
                    'id',
                    [
                        'label' => 'Numer seryjny urządzenia',
                        'value' => $model->device->sn,
                    ],
                    [
                        'label' => 'Flaga',
                        'value' => $model->flag->name,
                    ],
                    'ip:ntext',
                    'created',
                ],
            ])
            ?>

        </div>
    </div>
</div>